name: jpos_launcher
description: jpOS Launcher
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  path: ^1.8.3
  xdg_directories: ^1.0.3
  yaml: ^3.1.2
  yaru: ^1.1.0
  yaru_icons: ^2.2.1
  yaru_widgets: ^3.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/jpos.yaml
